CREATE TABLE IF NOT EXISTS postal_item(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(254) NOT NULL,
    addresseeIndex BIGINT NOT NULL,
    addresseeAddress VARCHAR(254) NOT NULL,
    addresseeName VARCHAR(254) NOT NULL,
    status VARCHAR(254) NOT NULL
    );

CREATE TABLE IF NOT EXISTS post_office(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    index BIGINT NOT NULL,
    name VARCHAR(254) NOT NULL,
    address VARCHAR(254) NOT NULL
    );

CREATE TABLE IF NOT EXISTS history(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postal_item_id BIGINT NOT NULL,
    post_office_id BIGINT,
    status VARCHAR(254) NOT NULL,
    CONSTRAINT fk_history_postal_item FOREIGN KEY(postal_item_id) REFERENCES postal_item(id) ON DELETE CASCADE,
    CONSTRAINT fk_history_post_office FOREIGN KEY(post_office_id) REFERENCES post_office(id) ON DELETE CASCADE
    );

